### ISSUE TITLE
Check timings on forced SIMD

### ISSUE THREAD

**Issue by ChrisRackauckas** [DDMGNI/GeomDAE.jl#3]
Have you checked timings when using the forced SIMD functions like the ones here?

https://github.com/DDMGNI/GeomDAE.jl/blob/master/src/utils/matrix_utils.jl#L22

Note that in Julia v0.5, LLVM will automatically apply SIMD to a loop like that when it recognizes it would increase performance (with `-O3`). So with that I've only seen `@simd` slow down codes.

**Comment by michakraus** [comment]
I had checked timings, but that was back with Julia v0.4.x. I just removed them and there isn't really any difference.
